navajo_water_wells:

  outputs:
    dev:
      type: duckdb
      path: raw_data/navajo_water_wells.duckdb
      extensions:
        - spatial
        - httpfs
        - postgres
      threads: 1
  target: dev